### ISSUE TITLE
Pretrained or Datasets?

### ISSUE THREAD

**Issue by MarioProjects** [pvitoria/ChromaGAN#1]
Hi,

FIrst of all thanks for your work! Could you provide some pretrained model or dataset?

Thanks.

**Comment by pvitoria** [comment]
Hi @MarioProjects,
We have trained the network in Imagenet dataset for 5 epochs.
You can download the dataset from the webpage of the authors.

About the pretrained model, we will upload them in the future.

**Comment by pvitoria** [comment]
Hi @MarioProjects , now you can find a link to the pretrained weights!

**Comment by MarioProjects** [comment]
Thanks! I have requested permission!
