### ISSUE TITLE
I cant get psnr in 25 by training this model ,atually only have 23.6.

### ISSUE THREAD

**Issue by XiaoluJiayou** [pvitoria/ChromaGAN#17]
I can't train to achieve the accuracy  for PSNR shown in the paper,do you have some tricks?

**Comment by XiaoluJiayou** [comment]
It actually only have 23.6 not achieve for 25.5. for imagenet

**Comment by pvitoria** [comment]
Hi,
I didn't use any trick that is not explained in the paper. 
I recommend you to use the pre trained weights.
