### ISSUE TITLE
C# implementation of ChromaGAN

### ISSUE THREAD

**Issue by GlebBrykin** [pvitoria/ChromaGAN#2]
Hi, pvitoria!

I implemented Your algorithm in C# for easy use in Windows OS. You can view it here: https://github.com/ColorfulSoft/StyleTransfer-Colorization-SuperResolution/tree/Russian/Colorization/2019.%20ChromaGAN

With best wishes,
Gleb Brykin

**Comment by pvitoria** [comment]
Hi Gleb! 
Thanks a lot for you interest and implementation! 

I will have a look in your code :)

If you have any question or anything to discuss let me know by email.

Best,
Patricia
