### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by git-artes** [pvitoria/ChromaGAN#3]
Hi, 
Thanks for sharing the code and preparing a colab demo, and congratulations for the project. 
I'm writing to you as I've tried using the second part of the demo (where one can use other images), but it complains about "Invalid Syntax" where it says `labimg_oritList = np.asarray(labimg_oritList)/255`. I've tried debugging it but I could not find the error...
Best
Federico

**Comment by laaRaa** [comment]
Hi,

Thanks for pointing out this issue. Indeed there is syntax error. After defining the function deprocess a line was pasted there by error. We updated the demo.

Best,
Lara

**Comment by git-artes** [comment]
Thanks!
