### ISSUE TITLE
Convert a single-channel grayscale image to 3 channels

### ISSUE THREAD

**Issue by GiantKevin** [pvitoria/ChromaGAN#4]
First of all, thank you for your paper and open source code, which gave me a lot of inspiration. When reading your code, I did not find how you converted the grayscale image into a three-channel input pre-trained vgg16 network. Can you tell me how to do it?

**Comment by pvitoria** [comment]
Hi @GiantKevin !

We just replicate the L channel 3 times. 

l_3=np.tile(trainL,[1,1,1,3])

Best,
Patricia
