### ISSUE TITLE
How to convert my_model_colorization.h5 to tensorfow lite model to cut model size?

### ISSUE THREAD

**Issue by rollmark** [pvitoria/ChromaGAN#6]
Hi, thanks for your great work, current pretraind model almost 800M, but my computer only 1G memory to use, how can i convert this keras model to tensorflow lite model, then i can load this model to memory to have fun, Thank you!

**Comment by pvitoria** [comment]
Hi @rollmark,
Sorry for the late reply.
We have no experience in tensorflow lite model. So we can not help there.
If you get to any solution let us know :)
Best,
Patricia
